export default {
  perspective: {
    width: '100%',
    height: '100%',
    position: 'relative',
    transformStyle: 'preserve-3d',
    perspective: 25,
    overflow: 'hidden',
  },

  ceiling: {
    display: 'flex',
    flexDirection: 'row',
    position: 'absolute',
    top: 0,
    left: 0,
    width: '300%',
    height: '100%',
    margin: '0 0 0 -100%',
    transformOrigin: 'top',
    transform: 'rotateX(-90deg)',
  },

  ceilingLeft: { width: '100%', height: '100%', display: 'flex', flexDirection: 'column' },
  ceilingTileAL: { width: '100%', height: '25%', background: '#ff007a', opacity: 0.9 },
  ceilingTileBL: { width: '100%', height: '100%', background: '#ff007a', opacity: 0.8 },
  ceilingTileCL: { width: '100%', height: '100%', background: '#ff007a', opacity: 0.7 },
  ceilingTileDL: { width: '100%', height: '100%', background: '#ff007a', opacity: 0.6 },
  ceilingTileEL: { width: '100%', height: '100%', background: '#ff007a', opacity: 0.5 },

  ceilingCenter: { width: '100%', height: '100%', display: 'flex', flexDirection: 'column' },
  ceilingTileA: { width: '100%', height: '25%', background: '#ff0000', opacity: 0.9 },
  ceilingTileB: { width: '100%', height: '100%', background: '#ff0000', opacity: 0.8 },
  ceilingTileC: { width: '100%', height: '100%', background: '#ff0000', opacity: 0.7 },
  ceilingTileD: { width: '100%', height: '100%', background: '#ff0000', opacity: 0.6 },
  ceilingTileE: { width: '100%', height: '100%', background: '#ff0000', opacity: 0.5 },

  ceilingRight: { width: '100%', height: '100%', display: 'flex', flexDirection: 'column' },
  ceilingTileAR: { width: '100%', height: '25%', background: '#ef00ff', opacity: 0.9 },
  ceilingTileBR: { width: '100%', height: '100%', background: '#ef00ff', opacity: 0.8 },
  ceilingTileCR: { width: '100%', height: '100%', background: '#ef00ff', opacity: 0.7 },
  ceilingTileDR: { width: '100%', height: '100%', background: '#ef00ff', opacity: 0.6 },
  ceilingTileER: { width: '100%', height: '100%', background: '#ef00ff', opacity: 0.5 },

  floor: {
    display: 'flex',
    flexDirection: 'row',
    position: 'absolute',
    bottom: 0,
    left: 0,
    width: '300%',
    height: '100%',
    margin: '0 0 0 -100%',
    transformOrigin: 'bottom',
    transform: 'rotateX(90deg)',
  },
  floorLeft: { width: '100%', height: '100%', display: 'flex', flexDirection: 'column-reverse' },
  floorTileAL: { width: '100%', height: '25%', background: '#ff007a', opacity: 0.9 },
  floorTileBL: { width: '100%', height: '100%', background: '#ff007a', opacity: 0.8 },
  floorTileCL: { width: '100%', height: '100%', background: '#ff007a', opacity: 0.7 },
  floorTileDL: { width: '100%', height: '100%', background: '#ff007a', opacity: 0.6 },
  floorTileEL: { width: '100%', height: '100%', background: '#ff007a', opacity: 0.5 },

  floorCenter: { width: '100%', height: '100%', display: 'flex', flexDirection: 'column-reverse' },
  floorTileA: { width: '100%', height: '25%', background: '#ff0000', opacity: 0.9 },
  floorTileB: { width: '100%', height: '100%', background: '#ff0000', opacity: 0.8 },
  floorTileC: { width: '100%', height: '100%', background: '#ff0000', opacity: 0.7 },
  floorTileD: { width: '100%', height: '100%', background: '#ff0000', opacity: 0.6 },
  floorTileE: { width: '100%', height: '100%', background: '#ff0000', opacity: 0.5 },

  floorRight: { width: '100%', height: '100%', display: 'flex', flexDirection: 'column-reverse' },
  floorTileAR: { width: '100%', height: '25%', background: '#ef00ff', opacity: 0.9 },
  floorTileBR: { width: '100%', height: '100%', background: '#ef00ff', opacity: 0.8 },
  floorTileCR: { width: '100%', height: '100%', background: '#ef00ff', opacity: 0.7 },
  floorTileDR: { width: '100%', height: '100%', background: '#ef00ff', opacity: 0.6 },
  floorTileER: { width: '100%', height: '100%', background: '#ef00ff', opacity: 0.5 },

  backWall: {
    position: 'absolute',
    top: 0,
    right: 0,
    width: '100%',
    height: '100%',
  },

  backWallForeground: {
    width: '100%',
    height: '100%',
    display: 'none',
    backgroundSize: '100%',
    transform: 'translateZ(-29px)',
  },

  backWallBackground: {
    width: '100%',
    height: '100%',
    backgroundSize: '100%',
    background: 'blue',
    transform: 'translateZ(-144px)',
  },

  rightWall: {
    display: 'flex',
    flexDirection: 'column',
    position: 'absolute',
    top: 0,
    right: 0,
    width: '100%',
    height: '100%',
    transformOrigin: 'right',
    transform: 'rotateY(-90deg)',
  },

  rightWallCenter: {
    width: '100%',
    height: '100%',
    display: 'flex',
    flexDirection: 'row-reverse',
  },
  rightWallTileA: { width: '25%', height: '100%', background: '#ff0000', opacity: 0.9 },
  rightWallTileB: { width: '100%', height: '100%', background: '#ff0000', opacity: 0.8 },
  rightWallTileC: { width: '100%', height: '100%', background: '#ff0000', opacity: 0.7 },
  rightWallTileD: { width: '100%', height: '100%', background: '#ff0000', opacity: 0.6 },
  rightWallTileE: { width: '100%', height: '100%', background: '#ff0000', opacity: 0.5 },

  leftWall: {
    display: 'flex',
    flexDirection: 'column',
    position: 'absolute',
    top: 0,
    left: 0,
    width: '100%',
    height: '100%',
    transformOrigin: 'left',
    transform: 'rotateY(90deg)',
  },

  leftWallCenter: {
    width: '100%',
    height: '100%',
    display: 'flex',
    flexDirection: 'row',
  },
  leftWallTileA: { width: '25%', height: '100%', background: '#ff0000', opacity: 0.9 },
  leftWallTileB: { width: '100%', height: '100%', background: '#ff0000', opacity: 0.8 },
  leftWallTileC: { width: '100%', height: '100%', background: '#ff0000', opacity: 0.7 },
  leftWallTileD: { width: '100%', height: '100%', background: '#ff0000', opacity: 0.6 },
  leftWallTileE: { width: '100%', height: '100%', background: '#ff0000', opacity: 0.5 },
};
