const actions = {
  TOGGLE: 'CHARACTER_CREATION_TOGGLE',
  TOGGLE_SUCCESS: 'CHARACTER_CREATION_TOGGLE_SUCCESS',
  TOGGLE_FAILURE: 'CHARACTER_CREATION_TOGGLE_FAILURE',
  toggle: () => ({
    type: actions.TOGGLE,
  }),

  SETATTR: 'CHARACTER_CREATION_SETATTR',
  SETATTR_SUCCESS: 'CHARACTER_CREATION_SETATTR_SUCCESS',
  SETATTR_FAILURE: 'CHARACTER_CREATION_SETATTR_FAILURE',
  setAttr: (key, val) => ({
    type: actions.SETATTR,
    payload: {
      [key]: val,
    },
  }),

  ADD_CHARACTER: 'CHARACTER_CREATION_ADD_CHARACTER',
  ADD_CHARACTER_SUCCESS: 'CHARACTER_CREATION_ADD_CHARACTER_SUCCESS',
  ADD_CHARACTER_FAILURE: 'CHARACTER_CREATION_ADD_CHARACTER_FAILURE',
  addCharacter: payload => ({
    type: actions.ADD_CHARACTER,
    payload,
  }),

  RESET: 'CHARACTER_CREATION_RESET',
  RESET_SUCCESS: 'CHARACTER_CREATION_RESET_SUCCESS',
  RESET_FAILURE: 'CHARACTER_CREATION_RESET_FAILURE',
  reset: () => ({
    type: actions.RESET,
  }),
};

export default actions;
